Added cr8tor failure handling logic (#42)
* remove dsstore
* add cr8tor failure handling logic
* parametrise lscsde references to github repository owner

diff --git a/.github/workflows/orchestrator.yml b/.github/workflows/orchestrator.yml
--- a/.github/workflows/orchestrator.yml
+++ b/.github/workflows/orchestrator.yml
@@ -39,8 +39,8 @@ jobs:
             - name: Create a new temp branch
               id: create_branch
               run: |
-                git config --global user.name "LSCSDE Governance Actions"
-                git config --global user.email "lscsde-actions@github.com"
+                git config --global user.name "${{ github.repository_owner }} Governance Actions"
+                git config --global user.email "${{ github.repository_owner }}-actions@github.com"
 
                 $timestamp = "$((Get-Date).ToString('yyyyMMddHHmmss'))"
                 $branchName = "temp-$timestamp-validate"
@@ -57,12 +57,12 @@ jobs:
             - name: Clone cr8tor repository (specific branch)
               if: ${{ inputs.cr8tor_branch != '' }}
               run: |
-                git clone --branch ${{ inputs.cr8tor_branch }} https://github.com/lsc-sde-crates/cr8tor.git
+                git clone --branch ${{ inputs.cr8tor_branch }} https://github.com/${{ github.repository_owner }}/cr8tor.git
 
             - name: Clone cr8tor repository (default branch)
               if: ${{ inputs.cr8tor_branch == '' }}
               run: |
-                git clone --branch develop https://github.com/lsc-sde-crates/cr8tor.git
+                git clone --branch develop https://github.com/${{ github.repository_owner }}/cr8tor.git
 
             - name: Sync cr8tor repository
               run: |
@@ -71,13 +71,28 @@ jobs:
             - name: Cr8tor CLI Create & Validate
               run: |
                 cr8tor\.venv\Scripts\activate
-                cr8tor create -a GithubAction -i ./resources
-                cr8tor validate -a GithubAction -i ./resources
+
+                # run cr8tor create and capture the error message
+                $errorMessage = cr8tor create -a GithubAction -i ./resources 2>&1 | Where-Object { $_ -is [System.Management.Automation.ErrorRecord] } | Out-String
+
+                if ($LASTEXITCODE -ne 0 -and $errorMessage -notlike "*can only be run once on a project*") {
+                  echo "::error::Cr8tor create failed: $errorMessage"
+                  echo "CR8TOR_ERROR=1" | Out-File -FilePath $env:GITHUB_ENV -Append
+                }
+                else {
+                  # run cr8tor validate and capture the error message
+                  $errorMessage = cr8tor validate -a GithubAction -i ./resources 2>&1 | Where-Object { $_ -is [System.Management.Automation.ErrorRecord] } | Out-String
+                  if ($LASTEXITCODE -ne 0) {
+                    echo "::error::Cr8tor validate failed: $errorMessage"
+                    echo "CR8TOR_ERROR=1" | Out-File -FilePath $env:GITHUB_ENV -Append
+                  }
+                }
+              continue-on-error: true
 
             - name: Push changes to repo
               run: |
-                git config --global user.name "LSCSDE Governance Actions"
-                git config --global user.email "lscsde-actions@github.com"
+                git config --global user.name "${{ github.repository_owner }} Governance Actions"
+                git config --global user.email "${{ github.repository_owner }}-actions@github.com"
 
                 git add ./bagit ./resources ./config.toml
                 git commit -m "Update after create and validate action"
@@ -108,9 +123,20 @@ jobs:
 
             - name: Send sign-off message
               run: |
-                $message = "Please verify and sign off DAR project at https://github.com/${{ github.repository }}/tree/${{ steps.create_branch.outputs.branch_name }}."
-                $message = $message + " Pull Request: ${{ steps.create_pr.outputs.pr_url }}"
-                echo "::notice::$message"
+                $repo_url = "https://github.com/${{ github.repository }}/tree/${{ steps.create_branch.outputs.branch_name }}"
+                if ($env:CR8TOR_ERROR -eq "1") {
+                  # Merge PR and delete temp branch
+                  gh pr merge --delete-branch --merge --admin
+
+                  $message = "Please analyse failures logged in the main branch."
+                  echo "::error::$message"
+                  exit 1
+                }
+                else {
+                  $message = "Please verify and sign off DAR project at $repo_url."
+                  $message = $message + " Pull Request: ${{ steps.create_pr.outputs.pr_url }}"
+                  echo "::notice::$message"
+                }
 
     SignOff:
         runs-on: ${{ inputs.environment }}-cr8tor-vm
@@ -132,7 +158,14 @@ jobs:
             - name: Cr8tor CLI Sign-Off
               run: |
                 cr8tor\.venv\Scripts\activate
-                cr8tor sign-off -a GithubAction -i ./resources -agreement ${{ needs.Validate.outputs.pr_url }} -signing-entity "cr8-ALL-projects-approver"
+
+                # run cr8tor sign-off and capture the error message
+                $errorMessage = cr8tor sign-off -a GithubAction -i ./resources -agreement ${{ needs.Validate.outputs.pr_url }} -signing-entity "cr8-ALL-projects-approver" 2>&1 | Where-Object { $_ -is [System.Management.Automation.ErrorRecord] } | Out-String
+                if ($LASTEXITCODE -ne 0) {
+                  echo "::error::Cr8tor sign-off failed: $errorMessage"
+                  echo "CR8TOR_ERROR=1" | Out-File -FilePath $env:GITHUB_ENV -Append
+                }
+              continue-on-error: true
 
             - name: Push changes to repository
               run: |
@@ -142,7 +175,14 @@ jobs:
 
             - name: Merge Pull Request and delete temp branch
               run: |
+                # Merge PR and delete temp branch
                 gh pr merge --delete-branch --merge --admin
+
+                if ($env:CR8TOR_ERROR -eq "1") {
+                  $message = "Please analyse failures logged in the main branch."
+                  echo "::error::$message"
+                  exit 1
+                }
 
             - name: Create artifact for signed off RO-Crate
               uses: actions/upload-artifact@v4
@@ -169,8 +209,8 @@ jobs:
             - name: Create a new temp branch
               id: create_branch
               run: |
-                git config --global user.name "LSCSDE Governance Actions"
-                git config --global user.email "lscsde-actions@github.com"
+                git config --global user.name "${{ github.repository_owner }} Governance Actions"
+                git config --global user.email "${{ github.repository_owner }}-actions@github.com"
 
                 $branchName = "temp-${{ needs.Validate.outputs.timestamp }}-stagetransfer"
                 git checkout -B $branchName
@@ -180,7 +220,15 @@ jobs:
             - name: Cr8tor CLI Staging Data
               run: |
                 cr8tor\.venv\Scripts\activate
-                cr8tor stage-transfer -a GithubAction -i ./resources
+
+                # run cr8tor stage-transfer and capture the error message
+                $errorMessage = cr8tor stage-transfer -a GithubAction -i ./resources 2>&1 | Where-Object { $_ -is [System.Management.Automation.ErrorRecord] } | Out-String
+                if ($LASTEXITCODE -ne 0) {
+                  echo "::error::Cr8tor stage-transfer failed: $errorMessage"
+                  echo "CR8TOR_ERROR=1" | Out-File -FilePath $env:GITHUB_ENV -Append
+                }
+              continue-on-error: true
+
 
             - name: Push changes to repo
               run: |
@@ -211,11 +259,22 @@ jobs:
                     ./resources
                     ./config.toml
 
-            - name: Send sign-off message
+            - name: Send disclosure message
               run: |
-                $message = "Please verify and approve Disclosure stage of DAR project at https://github.com/${{ github.repository }}/tree/${{ steps.create_branch.outputs.branch_name }}."
-                $message = $message + " Pull Request: ${{ steps.create_pr.outputs.pr_url }}"
-                echo "::notice::$message"
+                $repo_url = "https://github.com/${{ github.repository }}/tree/${{ steps.create_branch.outputs.branch_name }}"
+                if ($env:CR8TOR_ERROR -eq "1") {
+                  # Merge PR and delete temp branch
+                  gh pr merge --delete-branch --merge --admin
+
+                  $message = "Please analyse failures logged in the main branch."
+                  echo "::error::$message"
+                  exit 1
+                }
+                else {
+                  $message = "Please verify and approve Disclosure stage of DAR project at $repo_url."
+                  $message = $message + " Pull Request: ${{ steps.create_pr.outputs.pr_url }}"
+                  echo "::notice::$message"
+                }
 
     Disclosure:
         runs-on: ${{ inputs.environment }}-cr8tor-vm
@@ -237,7 +296,15 @@ jobs:
           - name: Cr8tor CLI Sign-Off
             run: |
               cr8tor\.venv\Scripts\activate
-              cr8tor disclosure -a GithubAction -i ./resources -agreement ${{ needs.Workflow-Execution.outputs.pr_url }} -signing-entity "cr8-ALL-projects-approver"
+
+              # run cr8tor disclosure and capture the error message
+              $errorMessage = cr8tor disclosure -a GithubAction -i ./resources -agreement ${{ needs.Workflow-Execution.outputs.pr_url }} -signing-entity "cr8-ALL-projects-approver" 2>&1 | Where-Object { $_ -is [System.Management.Automation.ErrorRecord] } | Out-String
+              if ($LASTEXITCODE -ne 0) {
+                echo "::error::Cr8tor disclosure failed: $errorMessage"
+                echo "CR8TOR_ERROR=1" | Out-File -FilePath $env:GITHUB_ENV -Append
+              }
+            continue-on-error: true
+
 
           - name: Push changes to repository
             run: |
@@ -247,7 +314,14 @@ jobs:
 
           - name: Merge Pull Request and delete temp branch
             run: |
+              # Merge PR and delete temp branch
               gh pr merge --delete-branch --merge --admin
+
+              if ($env:CR8TOR_ERROR -eq "1") {
+                $message = "Please analyse failures logged in the main branch."
+                echo "::error::$message"
+                exit 1
+              }
 
           - name: Create artifact for signed off RO-Crate
             uses: actions/upload-artifact@v4
@@ -272,8 +346,8 @@ jobs:
             - name: Create a new temp branch
               id: create_branch
               run: |
-                git config --global user.name "LSCSDE Governance Actions"
-                git config --global user.email "lscsde-actions@github.com"
+                git config --global user.name "${{ github.repository_owner }} Governance Actions"
+                git config --global user.email "${{ github.repository_owner }}-actions@github.com"
 
                 $branchName = "temp-${{ needs.Validate.outputs.timestamp }}-publish"
                 git checkout -B $branchName
@@ -283,7 +357,14 @@ jobs:
             - name: Cr8tor CLI Publish Data
               run: |
                 cr8tor\.venv\Scripts\activate
-                cr8tor publish -a GithubAction -i ./resources
+
+                # run cr8tor publish and capture the error message
+                $errorMessage = cr8tor publish -a GithubAction -i ./resources 2>&1 | Where-Object { $_ -is [System.Management.Automation.ErrorRecord] } | Out-String
+                if ($LASTEXITCODE -ne 0) {
+                  echo "::error::Cr8tor publish failed: $errorMessage"
+                  echo "CR8TOR_ERROR=1" | Out-File -FilePath $env:GITHUB_ENV -Append
+                }
+              continue-on-error: true
 
             - name: Create artifact for published RO-Crate
               uses: actions/upload-artifact@v4
@@ -315,7 +396,14 @@ jobs:
 
             - name: Merge Pull Request and delete temp branch
               run: |
+                # Merge PR and delete temp branch
                 gh pr merge --delete-branch --merge --admin
+
+                if ($env:CR8TOR_ERROR -eq "1") {
+                  $message = "Please analyse failures logged in the main branch."
+                  echo "::error::$message"
+                  exit 1
+                }
 
             - name: Send final message
               run: |
